freebsd_instance:
  image_family: freebsd-14-0-snap
  cpu: 2
  memory: 8G

task:
  name: Build aquaBSD test images
  timeout_in: 30m
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  setup_script:
  - export IGNORE_OSVERSION=yes
  - export SSL_NO_VERIFY_PEER=1
  - fetch https://github.com/inobulles/aquabsd-pkg-repo/releases/download/v0722a-beta/libcopyfile-0722a.pkg -o libcopyfile.pkg
  - ABI="FreeBSD:13:amd64" pkg add -M libcopyfile.pkg
  build_script:
  - sh build.sh
  test_script:
  - sh test.sh
  post_script:
  - ls -lah .build/
  - df -h
  image_artifacts:
    path: ".build/*"
