freebsd_instance:
  image_family: freebsd-14-0-snap
  cpu: 2
  memory: 8G

task:
  name: Build aquaBSD test images
  timeout_in: 30m
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  build_script:
  - sh build.sh
  test_script:
  - sh test.sh
  post_script:
  - ls -lah .build/
  - df -h
  image_artifacts:
    path: ".build/*"
