freebsd_instance:
  image_family: freebsd-14-0-snap
  cpu: 2
  memory: 4G

task:
  name: Build aquaBSD test images
  timeout_in: 30m
  env:
    CLICOLOR_FORCE:
  setup_script:
    - uname -a
    - df -h
    - pkg --version
    - pkg install -y git-lite
    - git clone https://github.com/inobulles/bob --depth 1 --branch main
    - ( cd bob && sh build.sh && sh-bin/bob install )
  build_script:
    - bob install
  test_script:
    - bob test
  post_script:
    - df -h
